POST http://localhost:5000/recipe
content-type: application/json

{
    "recipe_id" : "4",
    "recipe_name": "Yet Another Recipe", 
    "recipe_method" : "All-Grain", 
    "recipe_srm" : "10", 
    "recipe_batch_size" : "20",
    "recipe_rating" : "3",
    "recipe_description" : "Second Recipe",
    "style_id" : "2",
    "image_id" : "2",
    "ingredients" : {
        "malt" : [
            {
                "malt_id" : "15",
                "malt_ingred_qty" : "10"
            }
        ],
        "yeast" : [
            {
                "yeast_id" : "42",
                "yeast_ingred_qty" : "1",
                "yeast_ingred_starter" : "true",
                "yeast_ingred_time" : "14"
            },
                        {
                "yeast_id" : "43",
                "yeast_ingred_qty" : "3.2",
                "yeast_ingred_starter" : "true",
                "yeast_ingred_time" : "60"
            }
        ],
        "hops" : [
            {
                "hops_id" : "2",
                "hops_ingred_qty" : "2",
                "hops_ingred_time" : "15",
                "hops_ingred_use" : "Boil"
            }
        ],
        "other" : [
            {
                "other_id" : "2",
                "other_ingred_qty" : "2",
                "other_ingred_time" : "15"
            },
                        {
                "other_id" : "1",
                "other_ingred_qty" : "1",
                "other_ingred_time" : "15"
            }
        ]
    }
}

### Get All Recipes
GET http://localhost:5000/recipe

### Get Recipe by Recipe ID
GET http://localhost:5000/recipe/2

### Soft Delete a recipe
DELETE http://localhost:5000/recipe/1

